### ISSUE TITLE
patches still applicable for detecting wannacry

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/detect_wannacry#12]
I know this was a bug in windows ages ago, but my nodes recently starting to show up as "true" again after previously showing false.  Is there the possibility that a recent patch windows released has superceded the ones used in the detection mechanism and caused it to show as a false positve?

https://github.com/puppetlabs/detect_wannacry/blob/master/facts.d/wannacry_fact.ps1#L8

**Comment by SeanTecha** [comment]
Hi @logicminds, I'm trying to track down what happened here. Did you happen to discover more info? I was told that this could be because SMB is disabled altogether as well.

**Comment by SeanTecha** [comment]
@logicminds I added a whole bunch of KBs that also include the fix. Please report back if issue still persists. Thanks!
