### ISSUE TITLE
Windows 2008 (R2) support is spotty

### ISSUE THREAD

**Issue by rnelson0** [puppetlabs/detect_wannacry#2]
Apparently there are issues with Windows 2008 (R2) displaying the full list of installed HotFixes. I'm not sure about the underlying cause, but here is [another way to detect the hotfix list](https://bogner.sh/2017/05/how-to-check-if-ms17-010-has-already-been-installed/).

**Comment by rychannel** [comment]
The issue we're seeing with 2008 R2 is that we have different versions of PowerShell running on servers... Apparently PS 2 will say it's not vulnerable even if it doesn't see any of the KB's in the list

**Comment by rychannel** [comment]
So maybe the version of Powershell isn't a factor.  We updated pwoershell on a system and it still had the problem of not resolving whether it was vulnerable or not.

It seems to be the "if($patch)"  Not sure what makes the two servers I have different with 2008 R2, but with zero output, $patch acts as $false on one server and $true on another server
