### ISSUE TITLE
updated KBs

### ISSUE THREAD

**Issue by tek0011** [puppetlabs/detect_wannacry#9]
It appears that now all 2016 servers are showing as vulnerable.  I dont know why or what is expected, but I do know that the srv.sys file no longer exists on my server.  It looks to be replaced by srv2.sys.  Thus, (when, and however this happens) 2016 servers will show as `wannacry_vulnerable=true` .

**Comment by tek0011** [comment]
I have engaged MSFT Pro Support and let them know of this issue.

**Comment by tek0011** [comment]
Here is our fix:

http://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=8436b0ac-13c3-4047-9c60-e1fdba6cf918

KB4022715 supercedes KB4019472

**Comment by tek0011** [comment]
also for 2012 - KB4022726 - supercedes KB4019215
http://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=73f88405-aafc-4c89-8f03-df4b3144be53

soon as next pull request is complete, can close this.

**Comment by SeanTecha** [comment]
@tek0011 Thank you for the PRs!
